name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v2
        name: Checkout [main]
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: npm install
      - run: npx nx affected --target=lint --parallel
      - run: npx nx affected --target=analyze --parallel
      - run: npx nx affected --target=test --parallel
      - run: npx nx affected --target=build --parallel
  pr:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable' # or: 'beta', 'dev' or 'master'
      - run: npm install
      - run: npx nx affected --target=lint --parallel
      - run: npx nx affected --target=analyze --parallel
      - run: npx nx affected --target=test --parallel
      - run: npx nx affected --target=build --parallel
  release:
    runs-on: ubuntu-latest
    needs: [main]
    steps:
      - uses: actions/checkout@v2
        name: Checkout [main]
        with:
          fetch-depth: 0
      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npx nx run-many --target=version --all --releaseAs=prerelease --preid=alpha --push --baseBranch main
#      - run: npx nx --target=version --releaseAs=prerelease --preid=alpha --push --baseBranch main
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
