name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    name: Merged
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - name: Checkout Project
        uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: npm ci
      - name: Code Check & Lint
        run: npm run affected:lint -- --all

      - name: Test & Build Code
        run: |
          npm run affected:test -- --all
          npm run affected:build -- --all

  pr:
    name: Pull Request
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: npm ci

      - name: Code Lint
        run: npm run affected:lint -- --all

      - name: Test & Build Code
        run: |
          npm run affected:test -- --all
          npm run affected:build -- --all

  build-android:
    name: Build, Release & Publish
    runs-on: ubuntu-latest
    needs: [main]
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: npm ci

      - name: Build APK
        run: |
          npx nx run mobile:buildApk -- --target-platform android-arm,android-arm64 --release

  build-ios:
    name: Build, Release & Publish
    runs-on: macos-latest
    needs: [main]
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: npm ci

      - name: Build IPA
        run: |
          npx nx run mobile:buildIos --  --release --no-codesign

  release:
    name: Build, Release & Publish
    runs-on: macos-latest
    needs: [ main]
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: npm ci

      - name: Build Code
        run: |
          npm run affected:build -- --all
          npx nx run mobile:buildApk
          npx nx run mobile:buildIos

      - name: Build, Release on GitHub & Publish to NPM
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run release
